# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/khoa/Ameno/face_morphing_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/khoa/Ameno/face_morphing_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/khoa/Ameno/face_morphing_cpp/CMakeFiles /home/khoa/Ameno/face_morphing_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/khoa/Ameno/face_morphing_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named frame_extract

# Build rule for target.
frame_extract: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 frame_extract
.PHONY : frame_extract

# fast build rule for target.
frame_extract/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/frame_extract.dir/build.make CMakeFiles/frame_extract.dir/build
.PHONY : frame_extract/fast

frame_extract.o: frame_extract.cc.o
.PHONY : frame_extract.o

# target to build an object file
frame_extract.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/frame_extract.dir/build.make CMakeFiles/frame_extract.dir/frame_extract.cc.o
.PHONY : frame_extract.cc.o

frame_extract.i: frame_extract.cc.i
.PHONY : frame_extract.i

# target to preprocess a source file
frame_extract.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/frame_extract.dir/build.make CMakeFiles/frame_extract.dir/frame_extract.cc.i
.PHONY : frame_extract.cc.i

frame_extract.s: frame_extract.cc.s
.PHONY : frame_extract.s

# target to generate assembly for a file
frame_extract.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/frame_extract.dir/build.make CMakeFiles/frame_extract.dir/frame_extract.cc.s
.PHONY : frame_extract.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cc.s
.PHONY : main.cc.s

utils/delaunay_triangulation.o: utils/delaunay_triangulation.cc.o
.PHONY : utils/delaunay_triangulation.o

# target to build an object file
utils/delaunay_triangulation.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/delaunay_triangulation.cc.o
.PHONY : utils/delaunay_triangulation.cc.o

utils/delaunay_triangulation.i: utils/delaunay_triangulation.cc.i
.PHONY : utils/delaunay_triangulation.i

# target to preprocess a source file
utils/delaunay_triangulation.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/delaunay_triangulation.cc.i
.PHONY : utils/delaunay_triangulation.cc.i

utils/delaunay_triangulation.s: utils/delaunay_triangulation.cc.s
.PHONY : utils/delaunay_triangulation.s

# target to generate assembly for a file
utils/delaunay_triangulation.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/delaunay_triangulation.cc.s
.PHONY : utils/delaunay_triangulation.cc.s

utils/face_correspondences.o: utils/face_correspondences.cc.o
.PHONY : utils/face_correspondences.o

# target to build an object file
utils/face_correspondences.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/face_correspondences.cc.o
.PHONY : utils/face_correspondences.cc.o

utils/face_correspondences.i: utils/face_correspondences.cc.i
.PHONY : utils/face_correspondences.i

# target to preprocess a source file
utils/face_correspondences.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/face_correspondences.cc.i
.PHONY : utils/face_correspondences.cc.i

utils/face_correspondences.s: utils/face_correspondences.cc.s
.PHONY : utils/face_correspondences.s

# target to generate assembly for a file
utils/face_correspondences.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/face_correspondences.cc.s
.PHONY : utils/face_correspondences.cc.s

utils/face_morph.o: utils/face_morph.cc.o
.PHONY : utils/face_morph.o

# target to build an object file
utils/face_morph.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/face_morph.cc.o
.PHONY : utils/face_morph.cc.o

utils/face_morph.i: utils/face_morph.cc.i
.PHONY : utils/face_morph.i

# target to preprocess a source file
utils/face_morph.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/face_morph.cc.i
.PHONY : utils/face_morph.cc.i

utils/face_morph.s: utils/face_morph.cc.s
.PHONY : utils/face_morph.s

# target to generate assembly for a file
utils/face_morph.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/face_morph.cc.s
.PHONY : utils/face_morph.cc.s

utils/video_handler.o: utils/video_handler.cc.o
.PHONY : utils/video_handler.o

# target to build an object file
utils/video_handler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/video_handler.cc.o
.PHONY : utils/video_handler.cc.o

utils/video_handler.i: utils/video_handler.cc.i
.PHONY : utils/video_handler.i

# target to preprocess a source file
utils/video_handler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/video_handler.cc.i
.PHONY : utils/video_handler.cc.i

utils/video_handler.s: utils/video_handler.cc.s
.PHONY : utils/video_handler.s

# target to generate assembly for a file
utils/video_handler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils/video_handler.cc.s
.PHONY : utils/video_handler.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... frame_extract"
	@echo "... main"
	@echo "... frame_extract.o"
	@echo "... frame_extract.i"
	@echo "... frame_extract.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/delaunay_triangulation.o"
	@echo "... utils/delaunay_triangulation.i"
	@echo "... utils/delaunay_triangulation.s"
	@echo "... utils/face_correspondences.o"
	@echo "... utils/face_correspondences.i"
	@echo "... utils/face_correspondences.s"
	@echo "... utils/face_morph.o"
	@echo "... utils/face_morph.i"
	@echo "... utils/face_morph.s"
	@echo "... utils/video_handler.o"
	@echo "... utils/video_handler.i"
	@echo "... utils/video_handler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

